### PR TITLE
Stemmer for Hindi using rule based approach added.

### PR DESCRIPTION
**Pull request by arushidogra**
Paper followed : http://computing.open.ac.uk/Sites/EACLSouthAsia/Papers/p6-Ramanathan.pdf

### CODE REVIEW

**Comment by arushidogra** [comment]
@copyninja , can you see it?

**Comment by copyninja** [comment]
I think better to add some test so we can verify it is doing what it is supposed to do and also not breaking already existing code. Then we can merge the request. @stultus Can you also have a look?.. As you are the original author of this module.

**Comment by arushidogra** [comment]
I added some tests. They are working fine. 
PS : I made a mistake in the commit. It is "suffix" instead of "prefix"

**Comment by stultus** [comment]
@arushidogra , you can ammend the commit message, check this - https://help.github.com/articles/changing-a-commit-message/ 

 I've just checked the functionality (not code) and it is working 
for some inputs I gave. will test it more intensively and let you know by tomorrow. 

@copyninja , santhosh is the original author, not me

**Comment by arushidogra** [comment]
Actually, Since its a rule based approach, so it might not work on some cases. But it is working for most of the cases. 
@stultus : changed the commit message :D

**Comment by copyninja** [comment]
Please enable Trvais CI for testing. @stultus For some reason I was imagining you as author dunno why :)

**Comment by arushidogra** [comment]
Can you see once?

**Pull request merged**
