### PR TITLE
Stemmer for Punjabi using rule based approach added.

### PR DESCRIPTION
**Pull request by arushidogra**
Paper followed : http://www.aclweb.org/anthology/W11-3006

### CODE REVIEW

**Comment by arushidogra** [comment]
@copyninja , can you see?

**Comment by arushidogra** [comment]
@copyninja , can you see?

**Comment by arushidogra** [comment]
@copyninja , i cant figure out why the travis is failing. It gives perfect results otherwise.

**Comment by copyninja** [comment]
@arushidogra Is this not a valid PR?

**Comment by arushidogra** [comment]
@copyninja , I closed this PR and made a new PR.

**Comment by stultus** [comment]
@arushidogra  You should learn to fix the problems in an existing branch (PR) :) .  please follow. the workflow I gave you on the other PR thread.

**Comment by copyninja** [comment]
On Tue, Apr 5, 2016 at 3:48 PM, Hrishi notifications@github.com wrote:

> @arushidogra You should learn to fix the problems in an existing branch (PR) . please follow. the workflow I gave you on the other PR thread.

I completely agree with @stultus. Next time please follow the way of
git rather than doing like this.

## 

Vasudev Kamath
http://copyninja.info
copyninja@{frndk.de|vasudev.homelinux.net}

**Comment by arushidogra** [comment]
@stultus , @copyninja : Sorry, I will not repeat this mistake again.

**Pull request closed without merging**
