### PR TITLE
Stemmer for Punjabi using rule based approach added.

### PR DESCRIPTION
**Pull request by arushidogra**
Paper followed : http://www.aclweb.org/anthology/W11-3006

### CODE REVIEW

**Comment by arushidogra** [comment]
@copyninja 
The travis test fails for normalizer in python 3.3. It passes for all tests of python2.7 and pypy. 
So , should I remove python3.3 from .travils.yml?

**Comment by arushidogra** [comment]
@copyninja . can you see once?

**Comment by copyninja** [comment]
Yes please remove python3.3

**Comment by arushidogra** [comment]
I did the changes. The travis test passed.

**Pull request merged**
